### ISSUE TITLE
Timer object memory leak

### ISSUE THREAD

**Issue by Ssabin-devalore** [d3/d3-timer#24]
Hello,

i seem to have memory leak from using the transition which uses the Timer object.
it's seems to me like it doesn't clean it though i dont keep references to any transition.

I built a live updating graph with d3.js v4.4 and angularjs 1.4.8 displaying nodes and connections which uses transition on updates.

i found out i have memory leaks on my application whether it stays open when i'm on the tab & not on the tab for a long time, i also check with task manager.

i added a screenshot showing my memory heap snap shoot, the Timer object seems to not be cleaning up and i'm really stuck about this.
[Heap snapshot](https://i.stack.imgur.com/XkK41.png)
an update flow example:

```
$interval(() => {
    getSnapshot()
}, 30)

function getSnapshot(timestamp){
    let snapshotTs = timestamp ? timestamp : moment()
    getSnapshotFromServer(snapshotTs).then(data=>{
        graph = data.graph //contains all nodes and connections
        buildGraph(graph)
    })
}

buildGraph(){
    //build graph with connections and nodes using transition
    //we use tr
}
```

**Comment by mbostock** [comment]
Sorry, but this isn’t something I investigate without further isolation and a reproducible test case.

A common antipattern that can cause a memory leak is to have interrupting transitions that using [*transition*.remove](https://github.com/d3/d3-transition/blob/master/README.md#transition_remove). If you interrupt a transition that used *transition*.remove, the transition won’t remove the elements. The two standard ways of avoiding this problem with repeated transitions are:

1. Use [d3.interval](https://github.com/d3/d3-timer/blob/master/README.md#interval) rather than setInterval or setTimeout so as to guarantee consistent timing. Make sure that your interval delay is shorter than your transition duration.

2. When performing the [general update pattern](https://bl.ocks.org/mbostock/3808218), do not re-select and re-exit elements that were already exiting. For example, you can mark the exiting elements with a class to prevent them from being re-selected subsequently; see [@RandomEtc’s bl.ocks.org/5165219](http://bl.ocks.org/RandomEtc/5165219) for an example.

When reporting an issue, please include a link to a live example, preferably on [bl.ocks.org](http://bl.ocks.org) or [RunKit](https://runkit.com/npm/d3), or as a pull request in the [appropriate repository](https://github.com/d3) with new unit tests, that demonstrates that the described behavior is not the [expected behavior](https://github.com/d3/d3/blob/master/API.md). Use only the minimum amount of code necessary to reproduce the unexpected behavior.

A good bug report should **isolate specific methods** that exhibit unexpected behavior and precisely define how expectations were violated. What did you expect the method or methods to do, and how did the observed behavior differ? The more precisely you isolate the issue, the faster I can investigate.

Non-actionable bugs may be temporarily closed until you provide additional information. If you can’t isolate the bug any further, please let me know and I will try to help. However, I beg your patience: I must balance your request against many other responsibilities—fixing other bugs, answering other questions, new features, new documentation, *etc.* Please also consider asking for help on [Stack Overflow](https://stackoverflow.com/tags/d3.js).

If you have a question about D3’s behavior and want to discuss it with other users, also consider the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).

Thank you! 🤗
