### ISSUE TITLE
 `d3.timer()` is much slower than `setInterval( ... ,0.00001)`

### ISSUE THREAD

**Issue by FrankenApps** [d3/d3-timer#31]
I have build a little test App and I hoped that `d3.timer()` would make it much faster by using `requestAnimationFrame()`, but sadly the opposite is true. It is even slower than using `setInterval( ... ,0.00001)`. 

Ok the version with `d3.timer()` is more responsive, but thats not too impressive since its overall speed is much slower. In the attached video I tried to generate a random walk from prime numbers. But with both methods it simply is too slow...
Maybe I've done something wrong in my algorithm, so that `requestAnimationFrame()` can not be used, but I would not know what that could be.

A video comparing  `d3.timer()` and `setInterval( ... ,0.00001)` (`setInterval()` is on left side): [setInterval_vs_d3.timer.zip](https://github.com/d3/d3-timer/files/1444090/setInterval_vs_d3.timer.zip)

I have also made two fiddles:
1. With `d3.interval()`: [With d3](https://jsfiddle.net/s0um5Loo/)
2. And with `setInterval`, which is faster but still much slower than computing this without Graphics: [Standard JS](https://jsfiddle.net/ohn7403k/1/)

**Comment by mbostock** [comment]
The *delay* specified to [setInterval](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setInterval) is in milliseconds. The default behavior of [requestAnimationFrame](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame) is 60 FPS, which is equivalent to 16.67 milliseconds, rather than 0.00001 milliseconds as you have specified. However, values less than 10 ms to setInterval are typically treated as 10 ms; see the section [Reasons for delays longer than specified](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout#Reasons_for_delays_longer_than_specified).

So, in any case, it is expected that 60 FPS would be slower than 100 FPS. But I would also expect setInterval with a short delay to be less consistent than requestAnimationFrame, since the latter is synchronized with the refresh of the display. If you want something to run faster than 60 FPS, you probably want to move it to a WebWorker.

In any case, this isn’t a bug report or a feature request for D3; please use [Stack Overflow tag d3.js](https://stackoverflow.com/tags/d3.js) to ask for help. Although I make an effort to assist everyone that asks, I am not always available to provide help promptly or directly. Stack Overflow provides a better collaborative forum for self-help: tens of thousands of D3-related questions have already been asked there, and some answered questions may be relevant to you.

When asking for help, please include a link to a live example that demonstrates the issue, preferably on [bl.ocks.org](http://bl.ocks.org). It is often impossible to debug from code snippets alone. Isolate the issue and reduce your code as much as possible before asking for help. The less code you post, the easier it is for someone to debug, and the more likely you are to get a helpful response.

If you have a question about D3’s behavior and want to discuss it with other users, also consider the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).

Thank you! 🤗
